services:
  db:
    image: postgres:alpine
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    ports:
      - 5432:5432

  backend:
    build:
      ./
    env_file:
      - .env
    environment:
      DB_HOST: db
      DATABASE_URL: postgres://${DB_USER}:${DB_PASSWORD}@db:${DB_PORT}/${DB_DATABASE}
    ports:
      - 8000:8000
    depends_on:
      - db
    command: sh -c "npm run migrate-and-start"

  frontend:
    build:
      ./view
    ports:
      - 3000:3000
